spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book-db;database_to_upper=true

jimmer:
  language: kotlin
  micro-service-name: ${spring.application.name}
  show-sql: true
  pretty-sql: true
  executor-context-prefixes:
    - org.babyfish.jimmer.example.cloud.kt.book.BookService
  database-validation-mode: ERROR
  client:
    ts:
      path: /book-service-ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Openapi of store-service
          description: "`/book/{id}` accesses current service, `/book/{id}/detail` accesses all services"
          version: "0.8.100"

server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
